export type Skill = {
  id: string; // 👉 现在是 slug
  name: string;
  description: string;
  github_url: string;
  tags: string[];
  stars: number;
  created_at: string;
  updated_at?: string;
};

export const mockSkills: Skill[] = [
  // ====== 官方 / 大牛出品 ======
  {
    id: "superpowers",
    name: "superpowers",
    description: "将对话转变为结构化的软件工程流程，涵盖 TDD、系统调试、Git Worktree、代码审查等完整开发闭环",
    github_url: "https://github.com/obra/superpowers",
    tags: ["prompt-tuning", "workflow"],
    stars: 219000,
    created_at: "2025-10-28",
    updated_at: "2026-06-01",
  },
  {
    id: "andrej-karpathy-skills",
    name: "andrej-karpathy-skills",
    description: "Karpathy 总结的 LLM 编程常见陷阱：错误假设、过度复杂、无关编辑等问题，让模型先思考再动手",
    github_url: "https://github.com/multica-ai/andrej-karpathy-skills",
    tags: ["prompt-tuning"],
    stars: 169000,
    created_at: "2025-12-05",
    updated_at: "2026-05-20",
  },
  {
    id: "anthropics-skills",
    name: "anthropics-skills",
    description: "Anthropic 官方技能包：PDF/DOCX/XLSX/PPTX 文档处理、MCP Builder、Web Artifacts Builder 等",
    github_url: "https://github.com/anthropics/skills",
    tags: ["official", "document-processing", "mcp"],
    stars: 137000,
    created_at: "2025-10-15",
    updated_at: "2026-06-03",
  },
  {
    id: "mattpocock-skills",
    name: "mattpocock-skills",
    description: "TypeScript 教父 Matt Pocock 的实战技能包：/grill-me 强制对齐需求、/tdd 测试驱动、/diagnose 结构化调试",
    github_url: "https://github.com/mattpocock/skills",
    tags: ["engineering", "typescript", "tdd"],
    stars: 108400,
    created_at: "2025-11-20",
    updated_at: "2026-06-02",
  },
  {
    id: "addyosmani-agent-skills",
    name: "addyosmani-agent-skills",
    description: "Google Chrome 工程主管 Addy Osmani 的生产级工程技能：/spec → /plan → /build → /test → /review → /ship 全流程",
    github_url: "https://github.com/addyosmani/agent-skills",
    tags: ["engineering", "workflow", "frontend"],
    stars: 47000,
    created_at: "2025-12-15",
    updated_at: "2026-06-04",
  },
  {
    id: "vercel-agent-skills",
    name: "vercel-agent-skills",
    description: "Vercel 官方技能：React/Next.js 最佳实践（40+ 性能规则）、Web Design 指南、View Transitions、一键部署等",
    github_url: "https://github.com/vercel-labs/agent-skills",
    tags: ["official", "frontend", "react", "nextjs"],
    stars: 26700,
    created_at: "2025-12-08",
    updated_at: "2026-05-28",
  },

  // ====== 精选合集 ======
  {
    id: "composiohq-awesome-skills",
    name: "awesome-claude-skills",
    description: "ComposioHQ 维护的 1000+ 精选 Skills 合集，涵盖文档处理、开发工具、数据分析、创意媒体等全品类",
    github_url: "https://github.com/ComposioHQ/awesome-claude-skills",
    tags: ["curated-list", "marketplace"],
    stars: 59300,
    created_at: "2025-10-20",
    updated_at: "2026-06-05",
  },
  {
    id: "wshobson-agents",
    name: "wshobson/agents",
    description: "多平台插件市场：191 个 Agents + 155 个 Skills + 102 个 Slash Commands，覆盖架构、安全、数据、ML 等领域",
    github_url: "https://github.com/wshobson/agents",
    tags: ["marketplace", "agents", "orchestration"],
    stars: 36100,
    created_at: "2025-07-24",
    updated_at: "2026-06-01",
  },
  {
    id: "hesreallyhim-awesome",
    name: "awesome-claude-code",
    description: "GitHub 最大 Claude Code 精选列表（18K+ Star）：覆盖 Skills、Hooks、Slash Commands、Agent 编排等全方位资源",
    github_url: "https://github.com/hesreallyhim/awesome-claude-code",
    tags: ["curated-list", "awesome"],
    stars: 18216,
    created_at: "2025-06-15",
    updated_at: "2026-05-30",
  },
  {
    id: "voltagent-awesome-skills",
    name: "awesome-agent-skills",
    description: "VoltAgent 维护的 1100+ 官方 + 社区 Agent Skills，来自 Anthropic、Google、Vercel、Stripe、Cloudflare 等团队",
    github_url: "https://github.com/VoltAgent/awesome-agent-skills",
    tags: ["curated-list", "multi-agent"],
    stars: 17886,
    created_at: "2025-10-28",
    updated_at: "2026-06-03",
  },

  // ====== 效率工具 ======
  {
    id: "prompt-optimizer",
    name: "prompt-optimizer",
    description: "将模糊需求自动拆解为可优化、可执行的步骤，提升 AI 输出质量",
    github_url: "https://github.com/linshenkx/prompt-optimizer",
    tags: ["prompt-tuning"],
    stars: 30500,
    created_at: "2025-11-10",
    updated_at: "2026-05-15",
  },
  {
    id: "graphify",
    name: "graphify",
    description: "将代码库、SQL Schema、文档一键转为可查询知识图谱，支持 25 种语言，比直接读文件省 70 倍 Token",
    github_url: "https://github.com/safishamsi/graphify",
    tags: ["knowledge-graph", "code-analysis"],
    stars: 54124,
    created_at: "2025-11-05",
    updated_at: "2026-06-05",
  },
  {
    id: "skill-toolbox",
    name: "skill-toolbox",
    description: "28 合 1 技能工具箱：一次安装，按需激活。涵盖写作、安全审计、TDD、Playwright 测试、数据分析等",
    github_url: "https://github.com/weilsoun/skill-toolbox",
    tags: ["toolbox", "all-in-one"],
    stars: 10500,
    created_at: "2026-01-20",
    updated_at: "2026-05-25",
  },
  {
    id: "mr-prompter",
    name: "mr-prompter",
    description: "Prompt 工程利器：内置 63 种技巧、82 个模板，可生成、审计、优化任意 LLM 的提示词",
    github_url: "https://github.com/865x44/mr-prompter",
    tags: ["prompt-tuning", "prompt-engineering"],
    stars: 1500,
    created_at: "2026-02-10",
    updated_at: "2026-05-20",
  },

  // ====== 安全 ======
  {
    id: "trailofbits-skills",
    name: "trailofbits-skills",
    description: "Trail of Bits 安全研究团队的技能市场：CodeQL/Semgrep 静态分析、变体分析、智能合约审计、恶意软件检测",
    github_url: "https://github.com/trailofbits/skills",
    tags: ["security", "auditing", "static-analysis"],
    stars: 5300,
    created_at: "2026-01-08",
    updated_at: "2026-06-02",
  },
  {
    id: "snyk-agent-scan",
    name: "snyk-agent-scan",
    description: "Snyk 出品的 AI Agent 安全扫描器：检测 Skill 中的 Prompt 注入、恶意载荷、密钥泄露等 15+ 种安全风险",
    github_url: "https://github.com/snyk/agent-scan",
    tags: ["security", "scanner"],
    stars: 2500,
    created_at: "2026-02-15",
    updated_at: "2026-06-04",
  },

  // ====== 个人开发者出品 ======
  {
    id: "Waza",
    name: "Waza",
    description: "将工程习惯转换成 Claude 技能，相比 superpowers 更轻量、更适合个人项目",
    github_url: "https://github.com/tw93/Waza",
    tags: ["prompt-tuning", "lightweight"],
    stars: 5000,
    created_at: "2025-12-20",
    updated_at: "2026-04-15",
  },
  {
    id: "zhangruncheng-commands",
    name: "commands",
    description: "57 个生产级 Slash Commands：15 个 Workflow + 42 个工具命令，覆盖日常开发的方方面面",
    github_url: "https://github.com/zhangruncheng/commands",
    tags: ["slash-commands", "tools"],
    stars: 2100,
    created_at: "2026-01-25",
    updated_at: "2026-05-18",
  },
  {
    id: "peterhdd-agent-skills",
    name: "agent-skills",
    description: "9 大领域 Agent Skills：前端、后端、系统设计、DevOps、移动端、ML、安全，面面俱到",
    github_url: "https://github.com/PeterHdd/agent-skills",
    tags: ["engineering", "full-stack"],
    stars: 1800,
    created_at: "2026-03-01",
    updated_at: "2026-05-22",
  },
  {
    id: "self-improving-agent",
    name: "self-improving-agent",
    description: "记录你对 Claude 的每一次纠正，自动沉淀为经验规则，避免重复踩坑",
    github_url: "https://github.com/peterskoett/self-improving-agent",
    tags: ["Automation", "learning"],
    stars: 635,
    created_at: "2025-12-10",
    updated_at: "2026-03-20",
  },
  {
    id: "subinium-awesome",
    name: "awesome-claude-code",
    description: "精选 Claude Code 工具/Skills/插件/MCP Server 列表，仅收录 1000+ Star 的优质仓库",
    github_url: "https://github.com/subinium/awesome-claude-code",
    tags: ["curated-list", "quality-filter"],
    stars: 1200,
    created_at: "2026-02-28",
    updated_at: "2026-05-30",
  },
  {
    id: "karanb192-awesome-skills",
    name: "awesome-claude-skills",
    description: "社区驱动的 50+ 验证 Skills 合集，涵盖 TDD、调试、Git 工作流、文档处理，持续维护中",
    github_url: "https://github.com/karanb192/awesome-claude-skills",
    tags: ["curated-list", "verified"],
    stars: 353,
    created_at: "2025-11-15",
    updated_at: "2026-05-28",
  },
];